name: Run K6 Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install K6
      run: |
        sudo apt-get update
        sudo apt-get install -y k6

    - name: Run K6 Load Test
      run: |
        k6 run pestore_k6.js

    # - name: Upload K6 results to Grafana (optional)
    #   env:
    #     GRAFANA_API_KEY: ${{ secrets.GRAFANA_API_KEY }}
    #   run: |
    #     k6 run --out grafana=https://<your-grafana-instance>/api/v1/push test.js


